# Dataset-specific parameters for Hon_WTC11-benchmark_TF-Perturb-seq
# Use with: nextflow run main.nf -params-file params.yaml

# Pipeline parameters
ENABLE_DATA_HASHING: true
ENABLE_SCRUBLET: false
use_igvf_reference: true
is_10x3v3: false
reverse_complement_guides: true
spacer_tag: "TTAGCTCTTAAAC"

DUAL_GUIDE: false
REFERENCE_transcriptome: 'human'
REFERENCE_gtf_download_path: 'https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_46/gencode.v46.annotation.gtf.gz'

# QC parameters
QC_min_genes_per_cell: 500
QC_min_cells_per_gene: 0.05
QC_pct_mito: 20

# Guide assignment
Multiplicity_of_infection: 'high'
GUIDE_ASSIGNMENT_method: 'sceptre'
GUIDE_ASSIGNMENT_capture_method: 'CROP-seq'
GUIDE_ASSIGNMENT_cleanser_probability_threshold: 1
GUIDE_ASSIGNMENT_SCEPTRE_probability_threshold: 'default'
GUIDE_ASSIGNMENT_SCEPTRE_n_em_rep: 'default'

# Inference
INFERENCE_method: 'default'
INFERENCE_target_guide_pairing_strategy: 'default'
INFERENCE_max_target_distance_bp: 1000000
INFERENCE_SCEPTRE_side: 'both'
INFERENCE_SCEPTRE_grna_integration_strategy: 'union'
INFERENCE_SCEPTRE_resampling_approximation: 'skew_normal'
INFERENCE_SCEPTRE_control_group: 'default'
INFERENCE_SCEPTRE_resampling_mechanism: 'default'
INFERENCE_SCEPTRE_formula_object: 'default'

# Network
NETWORK_custom_central_nodes: 'undefined'
NETWORK_central_nodes_num: 1

# Resource limits
max_cpus: 128
max_memory: '256.GB'

# Google Cloud
google_bucket: 'gs://igvf-pertub-seq-pipeline-data'
google_project: 'igvf-pertub-seq-pipeline'
google_region: 'us-central1'
